project:
  type: website
  output-dir: docs

website:
  favicon: assets/favicon.ico
  title: "EOSE09"
  navbar:
    left:
      - href: lectures/lecture-1.qmd
        text: Lecture 1
      - href: labs/Lab-1.qmd
        text: Lab 1
      - href: labs/Lab-2.qmd
        text: Lab 2
  page-footer:
    center: |
      If you have any questions, please feel free to [contact me here {{< fa paper-plane >}}]({{< var email.contact >}})

format:
  html:
    theme:
    - flatly
    - custom.scss
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
