project:
  type: website
  output-dir: docs

website:
  favicon: assets/favicon.ico
  title: "{{< var title >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center: |
      If you have any questions, please feel free to [contact me here {{< fa paper-plane >}}]({{< var email.contact >}})

format: html

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
